// Default Labels
export enum LabelText {
  ADD_CATEGORY = 'Add category',
  COLLAPSE_CATEGORY = 'Collapse Category List',
  NOTES = 'Notes',
  CREATE_NEW_NOTE = 'Create new note',
  DELETE_PERMANENTLY = 'Delete permanently',
  DOWNLOAD = 'Download',
  FAVORITES = 'Favorites',
  SCRATCHPAD = 'Scratchpad',
  MARK_AS_FAVORITE = 'Mark as favorite',
  MOVE_TO_TRASH = 'Move to trash',
  NEW_CATEGORY = 'New category...',
  NEW_NOTE = 'New note',
  REMOVE_CATEGORY = 'Remove category',
  REMOVE_FAVORITE = 'Remove favorite',
  MOVE_CATEGORY = 'Move category',
  RESTORE_FROM_TRASH = 'Restore from trash',
  SETTINGS = 'Settings',
  SYNC_NOTES = 'Sync notes',
  TRASH = 'Trash',
  WELCOME_TO_TAKENOTE = 'Welcome to Takenote!',
  RENAME = 'Rename category',
  ADD_CONTENT_NOTE = 'Please add content to this new note to access the menu options.',
  DOWNLOAD_ALL_NOTES = 'Download all notes',
  BACKUP_ALL_NOTES = 'Export backup',
  IMPORT_BACKUP = 'Import backup',
  TOGGLE_FAVORITE = 'Toggle favorite',
  COPY_REFERENCE_TO_NOTE = 'Copy reference to note',
}

// export enum LabelText {
//   ADD_CATEGORY = '添加类目',
//   COLLAPSE_CATEGORY = '折叠类目列表',
//   NOTES = '笔记',
//   CREATE_NEW_NOTE = '新增笔记',
//   DELETE_PERMANENTLY = '永久删除',
//   DOWNLOAD = '下载',
//   FAVORITES = '喜爱',
//   SCRATCHPAD = '便签纸',
//   MARK_AS_FAVORITE = '标记为喜爱',
//   MOVE_TO_TRASH = '移到垃圾桶',
//   NEW_CATEGORY = '新增类目...',
//   NEW_NOTE = '新增笔记',
//   REMOVE_CATEGORY = '移除类目',
//   REMOVE_FAVORITE = '移除喜爱',
//   MOVE_CATEGORY = '移动类目',
//   RESTORE_FROM_TRASH = '从垃圾桶中恢复',
//   SETTINGS = '设置',
//   SYNC_NOTES = '同步笔记',
//   TRASH = '垃圾桶',
//   WELCOME_TO_TAKENOTE = '欢迎来到 Takenote!',
//   RENAME = '重命名类目',
//   ADD_CONTENT_NOTE = '请将内容添加到此新笔记中，以访问菜单选项。',
//   DOWNLOAD_ALL_NOTES = '下载所有笔记',
//   BACKUP_ALL_NOTES = '导出备份',
//   IMPORT_BACKUP = '导入备份',
//   TOGGLE_FAVORITE = '切换收藏',
//   COPY_REFERENCE_TO_NOTE = '将引用复制到笔记',
// }
